-- =============================================================================
-- 05 · 计费明细 usage_ledger
-- 一条小时聚合桶 → 一条计费明细；所有费率都是"当时快照"，事后改价不影响历史账
-- =============================================================================

CREATE TABLE IF NOT EXISTS usage_ledger (
  id                       BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  ledger_no                VARCHAR(48)     NOT NULL COMMENT '计费单号',
  user_id                  BIGINT UNSIGNED NOT NULL,
  provider_id              BIGINT UNSIGNED NOT NULL,
  node_id                  BIGINT UNSIGNED NOT NULL,
  binding_id               BIGINT UNSIGNED NOT NULL COMMENT '按流量发生时间命中的绑定',
  pricing_rule_id          BIGINT UNSIGNED NOT NULL COMMENT '按流量发生时间命中的定价规则',
  period_start             DATETIME(6)     NOT NULL COMMENT '计费周期起点(UTC)',
  period_end               DATETIME(6)     NOT NULL COMMENT '计费周期终点(UTC)',
  upload_bytes             BIGINT UNSIGNED NOT NULL DEFAULT 0,
  download_bytes           BIGINT UNSIGNED NOT NULL DEFAULT 0,
  billable_bytes           BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '计费字节=ROUND(上行*ur+下行*dr)',
  billable_gb              DECIMAL(30,8)   NOT NULL DEFAULT 0.00000000 COMMENT '计费GB=billable_bytes/1024^3',
  points_per_gb            DECIMAL(30,8)   NOT NULL COMMENT '计费时刻单价快照',
  upload_ratio             DECIMAL(10,6)   NOT NULL DEFAULT 1.000000 COMMENT '计费时刻上行系数快照',
  download_ratio           DECIMAL(10,6)   NOT NULL DEFAULT 1.000000 COMMENT '计费时刻下行系数快照',
  raw_points_amount        DECIMAL(30,8)   NOT NULL DEFAULT 0.00000000 COMMENT '按量原始值',
  user_points_amount       DECIMAL(30,8)   NOT NULL DEFAULT 0.00000000 COMMENT '实扣用户 points',
  platform_commission_rate DECIMAL(9,6)    NOT NULL DEFAULT 0.000000 COMMENT '计费时刻抽成快照',
  platform_points_amount   DECIMAL(30,8)   NOT NULL DEFAULT 0.00000000 COMMENT '平台抽成 points',
  provider_points_amount   DECIMAL(30,8)   NOT NULL DEFAULT 0.00000000 COMMENT '服务商应得=用户-平台',
  is_reversal              TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '1=红冲行',
  reversal_of_id           BIGINT UNSIGNED NULL COMMENT '被冲销的 usage_ledger.id',
  user_ledger_id           BIGINT UNSIGNED NULL COMMENT '对应 user_points_ledger.id',
  provider_ledger_id       BIGINT UNSIGNED NULL COMMENT '对应 provider_points_ledger.id',
  settlement_id            BIGINT UNSIGNED NULL COMMENT '已归属结算单(唯一结算由 settlement_items 保证)',
  status                   ENUM('pending','charged','skipped','failed','reversed') NOT NULL DEFAULT 'pending',
  idempotency_key          VARCHAR(128)    NOT NULL COMMENT '=SHA2(binding|node|period_start|period_end)',
  error_msg                VARCHAR(255)    NULL,
  metadata                 JSON            NULL,
  billed_at                DATETIME(6)     NULL,
  created_at               DATETIME(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at               DATETIME(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uk_ul_ledger_no (ledger_no),
  UNIQUE KEY uk_ul_idem      (idempotency_key),
  KEY idx_ul_user_time       (user_id, period_start),
  KEY idx_ul_provider_settle (provider_id, settlement_id, period_end),
  KEY idx_ul_status_time     (status, period_end),
  KEY idx_ul_binding         (binding_id, period_start),
  CONSTRAINT fk_ul_user     FOREIGN KEY (user_id)         REFERENCES users(id),
  CONSTRAINT fk_ul_provider FOREIGN KEY (provider_id)     REFERENCES providers(id),
  CONSTRAINT fk_ul_node     FOREIGN KEY (node_id)         REFERENCES provider_nodes(id),
  CONSTRAINT fk_ul_binding  FOREIGN KEY (binding_id)      REFERENCES user_provider_bindings(id),
  CONSTRAINT fk_ul_rule     FOREIGN KEY (pricing_rule_id) REFERENCES provider_pricing_rules(id),
  CONSTRAINT fk_ul_userled  FOREIGN KEY (user_ledger_id)  REFERENCES user_points_ledger(id),
  CONSTRAINT fk_ul_provled  FOREIGN KEY (provider_ledger_id) REFERENCES provider_points_ledger(id),
  CONSTRAINT ck_ul_win      CHECK (period_end > period_start),
  CONSTRAINT ck_ul_amounts  CHECK (is_reversal = 1 OR (user_points_amount >= 0 AND billable_gb >= 0)),
  CONSTRAINT ck_ul_split    CHECK (is_reversal = 1
                                   OR user_points_amount = platform_points_amount + provider_points_amount),
  CONSTRAINT ck_ul_meta     CHECK (metadata IS NULL OR JSON_VALID(metadata))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='流量计费明细(不可变,红冲修正)';
